version: "3"
services:
  pam:
    image: bryan501/pam23:ldap
    container_name: pam.edt.org
    hostname: pam.edt.org
    networks:
      - 2hisx
    privileged: true

  ldap:
    image: bryan501/ldap23:latestv2
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    networks:
      - 2hisx
networks:
  2hisx:

