version: "3"
services:
  ldap:
    image: bryan501/ldap23:latestv2
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
    networks:
      - 2hisx
  dav23:
    image: bryan501/dav23:git
    container_name: dav.edt.org
    hostname: dav.edt.org
    privileged: true
    ports:
      - "80:80"
    volumes:
      - "volum-dav:/var/www/webdav"
    networks:
      - 2hisx 
  pam:
    image: bryan501/pam23:latest
    container_name: pam.edt.org
    hostname: pem.edt.org
    privileged: true
    networks:
      - 2hisx
networks:
  2hisx:

volumes:
  volum-dav:
